// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/evm/bridge/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryAttestationStatusRequest struct {
	AttestationId string `protobuf:"bytes,1,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
}

func (m *QueryAttestationStatusRequest) Reset()         { *m = QueryAttestationStatusRequest{} }
func (m *QueryAttestationStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAttestationStatusRequest) ProtoMessage()    {}
func (*QueryAttestationStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c51747409f17890, []int{0}
}
func (m *QueryAttestationStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestationStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestationStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestationStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestationStatusRequest.Merge(m, src)
}
func (m *QueryAttestationStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestationStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestationStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestationStatusRequest proto.InternalMessageInfo

func (m *QueryAttestationStatusRequest) GetAttestationId() string {
	if m != nil {
		return m.AttestationId
	}
	return ""
}

type QueryAttestationStatusResponse struct {
	AttestationId string `protobuf:"bytes,1,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	Processed     bool   `protobuf:"varint,2,opt,name=processed,proto3" json:"processed,omitempty"`
}

func (m *QueryAttestationStatusResponse) Reset()         { *m = QueryAttestationStatusResponse{} }
func (m *QueryAttestationStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAttestationStatusResponse) ProtoMessage()    {}
func (*QueryAttestationStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c51747409f17890, []int{1}
}
func (m *QueryAttestationStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestationStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestationStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestationStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestationStatusResponse.Merge(m, src)
}
func (m *QueryAttestationStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestationStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestationStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestationStatusResponse proto.InternalMessageInfo

func (m *QueryAttestationStatusResponse) GetAttestationId() string {
	if m != nil {
		return m.AttestationId
	}
	return ""
}

func (m *QueryAttestationStatusResponse) GetProcessed() bool {
	if m != nil {
		return m.Processed
	}
	return false
}

func init() {
	proto.RegisterType((*QueryAttestationStatusRequest)(nil), "cosmos.evm.bridge.v1.QueryAttestationStatusRequest")
	proto.RegisterType((*QueryAttestationStatusResponse)(nil), "cosmos.evm.bridge.v1.QueryAttestationStatusResponse")
}

func init() { proto.RegisterFile("cosmos/evm/bridge/v1/query.proto", fileDescriptor_1c51747409f17890) }

var fileDescriptor_1c51747409f17890 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x31, 0x4b, 0x03, 0x41,
	0x10, 0x85, 0xb3, 0x01, 0xc5, 0x2c, 0x28, 0x78, 0x58, 0x84, 0x10, 0x97, 0x10, 0x10, 0xd2, 0x64,
	0x87, 0x18, 0xad, 0xac, 0xb4, 0x10, 0x52, 0x1a, 0x3b, 0x1b, 0xb9, 0xdc, 0x0d, 0x97, 0x05, 0xef,
	0xe6, 0x72, 0xb3, 0x77, 0x24, 0x88, 0x8d, 0xbf, 0x40, 0xf0, 0xe7, 0x58, 0x0b, 0x96, 0x01, 0x1b,
	0x4b, 0xc9, 0xf9, 0x43, 0xc4, 0x1c, 0x92, 0x88, 0x51, 0xb4, 0x9d, 0x99, 0xf7, 0x1e, 0xdf, 0x3c,
	0xd9, 0xf0, 0x88, 0x43, 0x62, 0xc0, 0x2c, 0x84, 0x41, 0x62, 0xfc, 0x00, 0x21, 0xeb, 0xc0, 0x28,
	0xc5, 0x64, 0xa2, 0xe3, 0x84, 0x2c, 0x39, 0x3b, 0xc5, 0x85, 0xc6, 0x2c, 0xd4, 0xc5, 0x85, 0xce,
	0x3a, 0xb5, 0x7a, 0x40, 0x14, 0x5c, 0x21, 0xb8, 0xb1, 0x01, 0x37, 0x8a, 0xc8, 0xba, 0xd6, 0x50,
	0xc4, 0x85, 0xa6, 0x79, 0x2a, 0x77, 0xcf, 0x3e, 0x2c, 0x8e, 0xad, 0x45, 0x2e, 0x56, 0xe7, 0xd6,
	0xb5, 0x29, 0xf7, 0x71, 0x94, 0x22, 0x5b, 0x67, 0x4f, 0x6e, 0xb9, 0x8b, 0xdd, 0xa5, 0xf1, 0xab,
	0xa2, 0x21, 0x5a, 0x95, 0xfe, 0xe6, 0xd2, 0xb4, 0xe7, 0x37, 0x51, 0xaa, 0x9f, 0x7c, 0x38, 0xa6,
	0x88, 0xf1, 0x8f, 0x46, 0x4e, 0x5d, 0x56, 0xe2, 0x84, 0x3c, 0x64, 0x46, 0xbf, 0x5a, 0x6e, 0x88,
	0xd6, 0x46, 0x7f, 0x31, 0xd8, 0x7f, 0x14, 0x72, 0x6d, 0x9e, 0xe3, 0x3c, 0x08, 0xb9, 0xfd, 0x2d,
	0xcc, 0xe9, 0xea, 0x55, 0x3f, 0xd0, 0xbf, 0x22, 0xd6, 0x0e, 0xfe, 0x27, 0x2a, 0x78, 0x9a, 0x47,
	0xb7, 0xcf, 0x6f, 0xf7, 0xe5, 0x43, 0xa7, 0x0b, 0x2b, 0x8b, 0x59, 0xa2, 0x62, 0xb8, 0xfe, 0x4a,
	0x7e, 0x73, 0xd2, 0x7b, 0x9a, 0x29, 0x31, 0x9d, 0x29, 0xf1, 0x3a, 0x53, 0xe2, 0x2e, 0x57, 0xa5,
	0x69, 0xae, 0x4a, 0x2f, 0xb9, 0x2a, 0x5d, 0x40, 0x60, 0xec, 0x30, 0x1d, 0x68, 0x8f, 0x42, 0x18,
	0x1b, 0xeb, 0x91, 0x89, 0xda, 0x94, 0x04, 0x10, 0x13, 0xb7, 0xbd, 0xa1, 0x6b, 0x22, 0x18, 0x7f,
	0xa6, 0xd8, 0x49, 0x8c, 0x3c, 0x58, 0x9f, 0x17, 0xd9, 0x7d, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x67,
	0xbb, 0xd9, 0x50, 0x20, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// AttestationStatus reports whether an attestation replay key was consumed.
	AttestationStatus(ctx context.Context, in *QueryAttestationStatusRequest, opts ...grpc.CallOption) (*QueryAttestationStatusResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) AttestationStatus(ctx context.Context, in *QueryAttestationStatusRequest, opts ...grpc.CallOption) (*QueryAttestationStatusResponse, error) {
	out := new(QueryAttestationStatusResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.bridge.v1.Query/AttestationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// AttestationStatus reports whether an attestation replay key was consumed.
	AttestationStatus(context.Context, *QueryAttestationStatusRequest) (*QueryAttestationStatusResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) AttestationStatus(ctx context.Context, req *QueryAttestationStatusRequest) (*QueryAttestationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttestationStatus not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_AttestationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAttestationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AttestationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.bridge.v1.Query/AttestationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AttestationStatus(ctx, req.(*QueryAttestationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.evm.bridge.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AttestationStatus",
			Handler:    _Query_AttestationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/evm/bridge/v1/query.proto",
}

func (m *QueryAttestationStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestationStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestationStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AttestationId) > 0 {
		i -= len(m.AttestationId)
		copy(dAtA[i:], m.AttestationId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AttestationId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAttestationStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestationStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestationStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Processed {
		i--
		if m.Processed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.AttestationId) > 0 {
		i -= len(m.AttestationId)
		copy(dAtA[i:], m.AttestationId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AttestationId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryAttestationStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AttestationId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAttestationStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AttestationId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Processed {
		n += 2
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryAttestationStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestationStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestationStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttestationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAttestationStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestationStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestationStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttestationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Processed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Processed = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
