// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/evm/bridge/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSubmitAttestation submits a fully signed testnet attestation for admission.
// It does not transfer, mint, lock, custody, or settle any tokens.
type MsgSubmitAttestation struct {
	Submitter     string   `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	RouteId       string   `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Direction     string   `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	SourceChainId string   `protobuf:"bytes,4,opt,name=source_chain_id,json=sourceChainId,proto3" json:"source_chain_id,omitempty"`
	SourceRef     string   `protobuf:"bytes,5,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	Nonce         uint64   `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Destination   string   `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`
	Amount        string   `protobuf:"bytes,8,opt,name=amount,proto3" json:"amount,omitempty"`
	DeadlineUnix  int64    `protobuf:"varint,9,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`
	Signatures    [][]byte `protobuf:"bytes,10,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (m *MsgSubmitAttestation) Reset()         { *m = MsgSubmitAttestation{} }
func (m *MsgSubmitAttestation) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitAttestation) ProtoMessage()    {}
func (*MsgSubmitAttestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d805a178fb0625ab, []int{0}
}
func (m *MsgSubmitAttestation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitAttestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitAttestation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitAttestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitAttestation.Merge(m, src)
}
func (m *MsgSubmitAttestation) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitAttestation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitAttestation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitAttestation proto.InternalMessageInfo

func (m *MsgSubmitAttestation) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgSubmitAttestation) GetRouteId() string {
	if m != nil {
		return m.RouteId
	}
	return ""
}

func (m *MsgSubmitAttestation) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *MsgSubmitAttestation) GetSourceChainId() string {
	if m != nil {
		return m.SourceChainId
	}
	return ""
}

func (m *MsgSubmitAttestation) GetSourceRef() string {
	if m != nil {
		return m.SourceRef
	}
	return ""
}

func (m *MsgSubmitAttestation) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *MsgSubmitAttestation) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *MsgSubmitAttestation) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgSubmitAttestation) GetDeadlineUnix() int64 {
	if m != nil {
		return m.DeadlineUnix
	}
	return 0
}

func (m *MsgSubmitAttestation) GetSignatures() [][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// MsgSubmitAttestationResponse returns the deterministic replay-protection ID.
type MsgSubmitAttestationResponse struct {
	AttestationId string `protobuf:"bytes,1,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
}

func (m *MsgSubmitAttestationResponse) Reset()         { *m = MsgSubmitAttestationResponse{} }
func (m *MsgSubmitAttestationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitAttestationResponse) ProtoMessage()    {}
func (*MsgSubmitAttestationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d805a178fb0625ab, []int{1}
}
func (m *MsgSubmitAttestationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitAttestationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitAttestationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitAttestationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitAttestationResponse.Merge(m, src)
}
func (m *MsgSubmitAttestationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitAttestationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitAttestationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitAttestationResponse proto.InternalMessageInfo

func (m *MsgSubmitAttestationResponse) GetAttestationId() string {
	if m != nil {
		return m.AttestationId
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgSubmitAttestation)(nil), "cosmos.evm.bridge.v1.MsgSubmitAttestation")
	proto.RegisterType((*MsgSubmitAttestationResponse)(nil), "cosmos.evm.bridge.v1.MsgSubmitAttestationResponse")
}

func init() { proto.RegisterFile("cosmos/evm/bridge/v1/tx.proto", fileDescriptor_d805a178fb0625ab) }

var fileDescriptor_d805a178fb0625ab = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0xa4, 0x49, 0x9b, 0xa3, 0x05, 0xf5, 0x14, 0xc1, 0x35, 0x6a, 0x2d, 0xab, 0x15,
	0x28, 0x8a, 0x14, 0x9f, 0x5a, 0xa4, 0x0e, 0x6c, 0x2d, 0x62, 0xc8, 0xd0, 0xc5, 0x15, 0x0b, 0x4b,
	0xe4, 0xf8, 0xae, 0xee, 0x49, 0xf8, 0x2e, 0xba, 0x77, 0x8e, 0xcc, 0x06, 0x8c, 0x4c, 0xec, 0x7c,
	0x89, 0x0c, 0x7c, 0x08, 0xc6, 0x8a, 0x89, 0x11, 0x25, 0x43, 0xbe, 0x06, 0xf2, 0xd9, 0x56, 0x22,
	0x91, 0x81, 0x25, 0xd2, 0xfb, 0xfd, 0xdf, 0xfb, 0xe7, 0xfc, 0x7f, 0x0f, 0x9f, 0xc4, 0x1a, 0x52,
	0x0d, 0x4c, 0xcc, 0x52, 0x36, 0x31, 0x92, 0x27, 0x82, 0xcd, 0xce, 0x99, 0xcd, 0x83, 0xa9, 0xd1,
	0x56, 0x93, 0x6e, 0x29, 0x07, 0x62, 0x96, 0x06, 0xa5, 0x1c, 0xcc, 0xce, 0x7b, 0x87, 0x51, 0x2a,
	0x95, 0x66, 0xee, 0xb7, 0x6c, 0xec, 0x3d, 0xaf, 0x7c, 0x52, 0x48, 0x0a, 0x83, 0x14, 0x92, 0x4a,
	0x38, 0x2a, 0x85, 0xb1, 0xab, 0x58, 0x65, 0xe7, 0x8a, 0xd3, 0xef, 0x4d, 0xdc, 0xbd, 0x81, 0xe4,
	0x36, 0x9b, 0xa4, 0xd2, 0x5e, 0x59, 0x2b, 0xc0, 0x46, 0x56, 0x6a, 0x45, 0x2e, 0x71, 0x07, 0x1c,
	0xb4, 0xc2, 0x50, 0xe4, 0xa3, 0x7e, 0xe7, 0x9a, 0xfe, 0xfa, 0x31, 0xac, 0x1f, 0x73, 0xc5, 0xb9,
	0x11, 0x00, 0xb7, 0xd6, 0x48, 0x95, 0x84, 0xeb, 0x56, 0x72, 0x84, 0xf7, 0x8c, 0xce, 0xac, 0x18,
	0x4b, 0x4e, 0x1f, 0x15, 0x63, 0xe1, 0xae, 0xab, 0x47, 0x9c, 0x1c, 0xe3, 0x0e, 0x97, 0x46, 0xc4,
	0x85, 0x3f, 0x6d, 0x3a, 0x6d, 0x0d, 0xc8, 0x4b, 0xfc, 0x14, 0x74, 0x66, 0x62, 0x31, 0x8e, 0xef,
	0x23, 0xa9, 0x8a, 0xf9, 0x1d, 0xd7, 0x73, 0x50, 0xe2, 0x37, 0x05, 0x1d, 0x71, 0x72, 0x82, 0x71,
	0xd5, 0x67, 0xc4, 0x1d, 0x6d, 0x95, 0x36, 0x25, 0x09, 0xc5, 0x1d, 0xe9, 0xe2, 0x96, 0xd2, 0x2a,
	0x16, 0xb4, 0xed, 0xa3, 0xfe, 0x4e, 0x58, 0x16, 0xc4, 0xc7, 0x8f, 0xb9, 0x00, 0x2b, 0x95, 0xfb,
	0x38, 0xba, 0xeb, 0xa6, 0x36, 0x11, 0x79, 0x86, 0xdb, 0x51, 0xaa, 0x33, 0x65, 0xe9, 0x9e, 0x13,
	0xab, 0x8a, 0x9c, 0xe1, 0x03, 0x2e, 0x22, 0xfe, 0x41, 0x2a, 0x31, 0xce, 0x94, 0xcc, 0x69, 0xc7,
	0x47, 0xfd, 0x66, 0xb8, 0x5f, 0xc3, 0x77, 0x4a, 0xe6, 0xc4, 0xc3, 0x18, 0x64, 0xa2, 0x22, 0x9b,
	0x19, 0x01, 0x14, 0xfb, 0xcd, 0xfe, 0x7e, 0xb8, 0x41, 0x5e, 0x5f, 0x7e, 0x59, 0xcd, 0x07, 0xeb,
	0x90, 0xbe, 0xae, 0xe6, 0x83, 0xb3, 0x5c, 0xda, 0x58, 0x4b, 0x55, 0x6f, 0x7c, 0xdb, 0x12, 0x4e,
	0xdf, 0xe2, 0xe3, 0x6d, 0x3c, 0x14, 0x30, 0xd5, 0x0a, 0x04, 0x79, 0x81, 0x9f, 0x44, 0x6b, 0x5c,
	0x44, 0x86, 0xca, 0xc8, 0x36, 0xe8, 0x88, 0x5f, 0x7c, 0x46, 0xb8, 0x79, 0x03, 0x09, 0x01, 0x7c,
	0xf8, 0xef, 0xa2, 0x07, 0xc1, 0xb6, 0xfb, 0x0a, 0xb6, 0xfd, 0x6f, 0xef, 0xe2, 0xff, 0x7b, 0xeb,
	0x37, 0xf6, 0x5a, 0x9f, 0x56, 0xf3, 0x01, 0xba, 0x1e, 0xfd, 0x5c, 0x78, 0xe8, 0x61, 0xe1, 0xa1,
	0x3f, 0x0b, 0x0f, 0x7d, 0x5b, 0x7a, 0x8d, 0x87, 0xa5, 0xd7, 0xf8, 0xbd, 0xf4, 0x1a, 0xef, 0x59,
	0x22, 0xed, 0x7d, 0x36, 0x09, 0x62, 0x9d, 0xb2, 0x2a, 0x94, 0xa1, 0x36, 0x09, 0x9b, 0x6a, 0x18,
	0xba, 0x53, 0x60, 0x79, 0x1d, 0x92, 0xfd, 0x38, 0x15, 0x30, 0x69, 0xbb, 0xd3, 0x7d, 0xf5, 0x37,
	0x00, 0x00, 0xff, 0xff, 0xba, 0x92, 0x39, 0xf8, 0x38, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SubmitAttestation validates a signed attestation without settlement.
	SubmitAttestation(ctx context.Context, in *MsgSubmitAttestation, opts ...grpc.CallOption) (*MsgSubmitAttestationResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitAttestation(ctx context.Context, in *MsgSubmitAttestation, opts ...grpc.CallOption) (*MsgSubmitAttestationResponse, error) {
	out := new(MsgSubmitAttestationResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.bridge.v1.Msg/SubmitAttestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SubmitAttestation validates a signed attestation without settlement.
	SubmitAttestation(context.Context, *MsgSubmitAttestation) (*MsgSubmitAttestationResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitAttestation(ctx context.Context, req *MsgSubmitAttestation) (*MsgSubmitAttestationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAttestation not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitAttestation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.bridge.v1.Msg/SubmitAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitAttestation(ctx, req.(*MsgSubmitAttestation))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.evm.bridge.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitAttestation",
			Handler:    _Msg_SubmitAttestation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/evm/bridge/v1/tx.proto",
}

func (m *MsgSubmitAttestation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitAttestation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitAttestation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signatures) > 0 {
		for iNdEx := len(m.Signatures) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Signatures[iNdEx])
			copy(dAtA[i:], m.Signatures[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Signatures[iNdEx])))
			i--
			dAtA[i] = 0x52
		}
	}
	if m.DeadlineUnix != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DeadlineUnix))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Destination) > 0 {
		i -= len(m.Destination)
		copy(dAtA[i:], m.Destination)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Destination)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Nonce != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x30
	}
	if len(m.SourceRef) > 0 {
		i -= len(m.SourceRef)
		copy(dAtA[i:], m.SourceRef)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceRef)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SourceChainId) > 0 {
		i -= len(m.SourceChainId)
		copy(dAtA[i:], m.SourceChainId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceChainId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Direction) > 0 {
		i -= len(m.Direction)
		copy(dAtA[i:], m.Direction)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Direction)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RouteId) > 0 {
		i -= len(m.RouteId)
		copy(dAtA[i:], m.RouteId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RouteId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitAttestationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitAttestationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitAttestationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AttestationId) > 0 {
		i -= len(m.AttestationId)
		copy(dAtA[i:], m.AttestationId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AttestationId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitAttestation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RouteId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Direction)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SourceChainId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SourceRef)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovTx(uint64(m.Nonce))
	}
	l = len(m.Destination)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DeadlineUnix != 0 {
		n += 1 + sovTx(uint64(m.DeadlineUnix))
	}
	if len(m.Signatures) > 0 {
		for _, b := range m.Signatures {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSubmitAttestationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AttestationId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitAttestation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitAttestation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitAttestation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RouteId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RouteId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Direction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Direction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceRef", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceRef = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Destination = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeadlineUnix", wireType)
			}
			m.DeadlineUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeadlineUnix |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signatures = append(m.Signatures, make([]byte, postIndex-iNdEx))
			copy(m.Signatures[len(m.Signatures)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitAttestationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitAttestationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitAttestationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttestationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
