// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mempool "github.com/cosmos/cosmos-sdk/types/mempool"
	mock "github.com/stretchr/testify/mock"

	txpool "github.com/cosmos/evm/mempool/txpool"

	types "github.com/cosmos/cosmos-sdk/types"
)

// Mempool is an autogenerated mock type for the Mempool type
type Mempool struct {
	mock.Mock
}

type Mempool_Expecter struct {
	mock *mock.Mock
}

func (_m *Mempool) EXPECT() *Mempool_Expecter {
	return &Mempool_Expecter{mock: &_m.Mock}
}

// CountTx provides a mock function with no fields
func (_m *Mempool) CountTx() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountTx")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Mempool_CountTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountTx'
type Mempool_CountTx_Call struct {
	*mock.Call
}

// CountTx is a helper method to define mock.On call
func (_e *Mempool_Expecter) CountTx() *Mempool_CountTx_Call {
	return &Mempool_CountTx_Call{Call: _e.mock.On("CountTx")}
}

func (_c *Mempool_CountTx_Call) Run(run func()) *Mempool_CountTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mempool_CountTx_Call) Return(_a0 int) *Mempool_CountTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mempool_CountTx_Call) RunAndReturn(run func() int) *Mempool_CountTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetTxPool provides a mock function with no fields
func (_m *Mempool) GetTxPool() *txpool.TxPool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTxPool")
	}

	var r0 *txpool.TxPool
	if rf, ok := ret.Get(0).(func() *txpool.TxPool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*txpool.TxPool)
		}
	}

	return r0
}

// Mempool_GetTxPool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTxPool'
type Mempool_GetTxPool_Call struct {
	*mock.Call
}

// GetTxPool is a helper method to define mock.On call
func (_e *Mempool_Expecter) GetTxPool() *Mempool_GetTxPool_Call {
	return &Mempool_GetTxPool_Call{Call: _e.mock.On("GetTxPool")}
}

func (_c *Mempool_GetTxPool_Call) Run(run func()) *Mempool_GetTxPool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mempool_GetTxPool_Call) Return(_a0 *txpool.TxPool) *Mempool_GetTxPool_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mempool_GetTxPool_Call) RunAndReturn(run func() *txpool.TxPool) *Mempool_GetTxPool_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *Mempool) Insert(_a0 context.Context, _a1 types.Tx) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.Tx) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mempool_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type Mempool_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 types.Tx
func (_e *Mempool_Expecter) Insert(_a0 interface{}, _a1 interface{}) *Mempool_Insert_Call {
	return &Mempool_Insert_Call{Call: _e.mock.On("Insert", _a0, _a1)}
}

func (_c *Mempool_Insert_Call) Run(run func(_a0 context.Context, _a1 types.Tx)) *Mempool_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.Tx))
	})
	return _c
}

func (_c *Mempool_Insert_Call) Return(_a0 error) *Mempool_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mempool_Insert_Call) RunAndReturn(run func(context.Context, types.Tx) error) *Mempool_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: _a0
func (_m *Mempool) Remove(_a0 types.Tx) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Tx) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mempool_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type Mempool_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - _a0 types.Tx
func (_e *Mempool_Expecter) Remove(_a0 interface{}) *Mempool_Remove_Call {
	return &Mempool_Remove_Call{Call: _e.mock.On("Remove", _a0)}
}

func (_c *Mempool_Remove_Call) Run(run func(_a0 types.Tx)) *Mempool_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Tx))
	})
	return _c
}

func (_c *Mempool_Remove_Call) Return(_a0 error) *Mempool_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mempool_Remove_Call) RunAndReturn(run func(types.Tx) error) *Mempool_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function with given fields: _a0, _a1
func (_m *Mempool) Select(_a0 context.Context, _a1 [][]byte) mempool.Iterator {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 mempool.Iterator
	if rf, ok := ret.Get(0).(func(context.Context, [][]byte) mempool.Iterator); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mempool.Iterator)
		}
	}

	return r0
}

// Mempool_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type Mempool_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 [][]byte
func (_e *Mempool_Expecter) Select(_a0 interface{}, _a1 interface{}) *Mempool_Select_Call {
	return &Mempool_Select_Call{Call: _e.mock.On("Select", _a0, _a1)}
}

func (_c *Mempool_Select_Call) Run(run func(_a0 context.Context, _a1 [][]byte)) *Mempool_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([][]byte))
	})
	return _c
}

func (_c *Mempool_Select_Call) Return(_a0 mempool.Iterator) *Mempool_Select_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mempool_Select_Call) RunAndReturn(run func(context.Context, [][]byte) mempool.Iterator) *Mempool_Select_Call {
	_c.Call.Return(run)
	return _c
}

// NewMempool creates a new instance of Mempool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMempool(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Mempool {
	mock := &Mempool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
