// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/evm/validatorincentives/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60e6116e01e2c5ae, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Authority             string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	AnnualRateBasisPoints uint32 `protobuf:"varint,2,opt,name=annual_rate_basis_points,json=annualRateBasisPoints,proto3" json:"annual_rate_basis_points,omitempty"`
	BlocksPerYear         uint64 `protobuf:"varint,3,opt,name=blocks_per_year,json=blocksPerYear,proto3" json:"blocks_per_year,omitempty"`
	RewardPeriodBlocks    uint64 `protobuf:"varint,4,opt,name=reward_period_blocks,json=rewardPeriodBlocks,proto3" json:"reward_period_blocks,omitempty"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60e6116e01e2c5ae, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *QueryParamsResponse) GetAnnualRateBasisPoints() uint32 {
	if m != nil {
		return m.AnnualRateBasisPoints
	}
	return 0
}

func (m *QueryParamsResponse) GetBlocksPerYear() uint64 {
	if m != nil {
		return m.BlocksPerYear
	}
	return 0
}

func (m *QueryParamsResponse) GetRewardPeriodBlocks() uint64 {
	if m != nil {
		return m.RewardPeriodBlocks
	}
	return 0
}

type QueryPeriodRequest struct {
}

func (m *QueryPeriodRequest) Reset()         { *m = QueryPeriodRequest{} }
func (m *QueryPeriodRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPeriodRequest) ProtoMessage()    {}
func (*QueryPeriodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60e6116e01e2c5ae, []int{2}
}
func (m *QueryPeriodRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPeriodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPeriodRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPeriodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPeriodRequest.Merge(m, src)
}
func (m *QueryPeriodRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPeriodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPeriodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPeriodRequest proto.InternalMessageInfo

type QueryPeriodResponse struct {
	Active                      bool   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	StartBlock                  uint64 `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock                    uint64 `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	AnnualRateBasisPoints       uint32 `protobuf:"varint,4,opt,name=annual_rate_basis_points,json=annualRateBasisPoints,proto3" json:"annual_rate_basis_points,omitempty"`
	EligibleBondedAtomic        string `protobuf:"bytes,5,opt,name=eligible_bonded_atomic,json=eligibleBondedAtomic,proto3" json:"eligible_bonded_atomic,omitempty"`
	CommittedAnnualBudgetAtomic string `protobuf:"bytes,6,opt,name=committed_annual_budget_atomic,json=committedAnnualBudgetAtomic,proto3" json:"committed_annual_budget_atomic,omitempty"`
	PeriodProvisionAtomic       string `protobuf:"bytes,7,opt,name=period_provision_atomic,json=periodProvisionAtomic,proto3" json:"period_provision_atomic,omitempty"`
	DistributedAtomic           string `protobuf:"bytes,8,opt,name=distributed_atomic,json=distributedAtomic,proto3" json:"distributed_atomic,omitempty"`
	TotalDistributedAtomic      string `protobuf:"bytes,9,opt,name=total_distributed_atomic,json=totalDistributedAtomic,proto3" json:"total_distributed_atomic,omitempty"`
}

func (m *QueryPeriodResponse) Reset()         { *m = QueryPeriodResponse{} }
func (m *QueryPeriodResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPeriodResponse) ProtoMessage()    {}
func (*QueryPeriodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60e6116e01e2c5ae, []int{3}
}
func (m *QueryPeriodResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPeriodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPeriodResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPeriodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPeriodResponse.Merge(m, src)
}
func (m *QueryPeriodResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPeriodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPeriodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPeriodResponse proto.InternalMessageInfo

func (m *QueryPeriodResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *QueryPeriodResponse) GetStartBlock() uint64 {
	if m != nil {
		return m.StartBlock
	}
	return 0
}

func (m *QueryPeriodResponse) GetEndBlock() uint64 {
	if m != nil {
		return m.EndBlock
	}
	return 0
}

func (m *QueryPeriodResponse) GetAnnualRateBasisPoints() uint32 {
	if m != nil {
		return m.AnnualRateBasisPoints
	}
	return 0
}

func (m *QueryPeriodResponse) GetEligibleBondedAtomic() string {
	if m != nil {
		return m.EligibleBondedAtomic
	}
	return ""
}

func (m *QueryPeriodResponse) GetCommittedAnnualBudgetAtomic() string {
	if m != nil {
		return m.CommittedAnnualBudgetAtomic
	}
	return ""
}

func (m *QueryPeriodResponse) GetPeriodProvisionAtomic() string {
	if m != nil {
		return m.PeriodProvisionAtomic
	}
	return ""
}

func (m *QueryPeriodResponse) GetDistributedAtomic() string {
	if m != nil {
		return m.DistributedAtomic
	}
	return ""
}

func (m *QueryPeriodResponse) GetTotalDistributedAtomic() string {
	if m != nil {
		return m.TotalDistributedAtomic
	}
	return ""
}

type QueryTreasuryRequest struct {
}

func (m *QueryTreasuryRequest) Reset()         { *m = QueryTreasuryRequest{} }
func (m *QueryTreasuryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTreasuryRequest) ProtoMessage()    {}
func (*QueryTreasuryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60e6116e01e2c5ae, []int{4}
}
func (m *QueryTreasuryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTreasuryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTreasuryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTreasuryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTreasuryRequest.Merge(m, src)
}
func (m *QueryTreasuryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTreasuryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTreasuryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTreasuryRequest proto.InternalMessageInfo

type QueryTreasuryResponse struct {
	Denom         string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	BalanceAtomic string `protobuf:"bytes,2,opt,name=balance_atomic,json=balanceAtomic,proto3" json:"balance_atomic,omitempty"`
}

func (m *QueryTreasuryResponse) Reset()         { *m = QueryTreasuryResponse{} }
func (m *QueryTreasuryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTreasuryResponse) ProtoMessage()    {}
func (*QueryTreasuryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60e6116e01e2c5ae, []int{5}
}
func (m *QueryTreasuryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTreasuryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTreasuryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTreasuryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTreasuryResponse.Merge(m, src)
}
func (m *QueryTreasuryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTreasuryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTreasuryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTreasuryResponse proto.InternalMessageInfo

func (m *QueryTreasuryResponse) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *QueryTreasuryResponse) GetBalanceAtomic() string {
	if m != nil {
		return m.BalanceAtomic
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmos.evm.validatorincentives.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmos.evm.validatorincentives.v1.QueryParamsResponse")
	proto.RegisterType((*QueryPeriodRequest)(nil), "cosmos.evm.validatorincentives.v1.QueryPeriodRequest")
	proto.RegisterType((*QueryPeriodResponse)(nil), "cosmos.evm.validatorincentives.v1.QueryPeriodResponse")
	proto.RegisterType((*QueryTreasuryRequest)(nil), "cosmos.evm.validatorincentives.v1.QueryTreasuryRequest")
	proto.RegisterType((*QueryTreasuryResponse)(nil), "cosmos.evm.validatorincentives.v1.QueryTreasuryResponse")
}

func init() {
	proto.RegisterFile("cosmos/evm/validatorincentives/v1/query.proto", fileDescriptor_60e6116e01e2c5ae)
}

var fileDescriptor_60e6116e01e2c5ae = []byte{
	// 667 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xae, 0xdb, 0x34, 0x37, 0x99, 0xab, 0xde, 0xab, 0x3b, 0x37, 0x0d, 0x56, 0x5b, 0x99, 0x12,
	0x09, 0x54, 0x54, 0xc5, 0xa6, 0x14, 0xda, 0x2e, 0xd8, 0x34, 0xf0, 0x00, 0xc1, 0xaa, 0x90, 0x60,
	0x63, 0x8d, 0xed, 0x51, 0x3a, 0xc2, 0x9e, 0x71, 0x67, 0xc6, 0xa6, 0xd9, 0xf2, 0x04, 0x48, 0x48,
	0x3c, 0x04, 0x4b, 0x9e, 0x80, 0x15, 0x62, 0x59, 0x89, 0x0d, 0x4b, 0xd4, 0xf2, 0x20, 0x28, 0x67,
	0xc6, 0xf4, 0x87, 0xaa, 0x6d, 0x96, 0x3e, 0xdf, 0xf7, 0x9d, 0xf3, 0x9d, 0x73, 0x7c, 0x06, 0xf5,
	0x13, 0xa1, 0x72, 0xa1, 0x02, 0x5a, 0xe5, 0x41, 0x45, 0x32, 0x96, 0x12, 0x2d, 0x24, 0xe3, 0x09,
	0xe5, 0x9a, 0x55, 0x54, 0x05, 0xd5, 0x46, 0x70, 0x50, 0x52, 0x39, 0xf6, 0x0b, 0x29, 0xb4, 0xc0,
	0x77, 0x0c, 0xdd, 0xa7, 0x55, 0xee, 0x5f, 0x42, 0xf7, 0xab, 0x8d, 0xa5, 0x95, 0x91, 0x10, 0xa3,
	0x8c, 0x06, 0xa4, 0x60, 0x01, 0xe1, 0x5c, 0x68, 0xa2, 0x99, 0xe0, 0xca, 0x24, 0xe8, 0x75, 0x10,
	0x7e, 0x3e, 0xc9, 0x37, 0x24, 0x92, 0xe4, 0x2a, 0xa4, 0x07, 0x25, 0x55, 0xba, 0xf7, 0xc5, 0x41,
	0xff, 0x9f, 0x0b, 0xab, 0x42, 0x70, 0x45, 0xf1, 0x0a, 0x6a, 0x93, 0x52, 0xef, 0x0b, 0xc9, 0xf4,
	0xd8, 0x75, 0x56, 0x9d, 0xb5, 0x76, 0x78, 0x1a, 0xc0, 0xdb, 0xc8, 0x25, 0x9c, 0x97, 0x24, 0x8b,
	0x24, 0xd1, 0x34, 0x8a, 0x89, 0x62, 0x2a, 0x2a, 0x04, 0xe3, 0x5a, 0xb9, 0xb3, 0xab, 0xce, 0xda,
	0x42, 0xb8, 0x68, 0xf0, 0x90, 0x68, 0x3a, 0x98, 0xa0, 0x43, 0x00, 0xf1, 0x3d, 0xf4, 0x6f, 0x9c,
	0x89, 0xe4, 0xb5, 0x8a, 0x0a, 0x2a, 0xa3, 0x31, 0x25, 0xd2, 0x9d, 0x5b, 0x75, 0xd6, 0x1a, 0xe1,
	0x82, 0x09, 0x0f, 0xa9, 0x7c, 0x49, 0x89, 0xc4, 0x0f, 0x50, 0x47, 0xd2, 0x37, 0x44, 0xa6, 0x13,
	0x1e, 0x13, 0x69, 0x64, 0x60, 0xb7, 0x01, 0x64, 0x6c, 0xb0, 0x21, 0x40, 0x03, 0x40, 0x4e, 0xdb,
	0x83, 0x60, 0xdd, 0xde, 0xe7, 0xb9, 0xba, 0x3d, 0x1b, 0xb6, 0xed, 0x75, 0x51, 0x93, 0x24, 0x93,
	0xc1, 0x41, 0x6f, 0xad, 0xd0, 0x7e, 0xe1, 0xdb, 0xe8, 0x6f, 0xa5, 0x89, 0xd4, 0xa6, 0x1e, 0xf4,
	0xd2, 0x08, 0x11, 0x84, 0xa0, 0x0e, 0x5e, 0x46, 0x6d, 0xca, 0xad, 0x1d, 0x6b, 0xbd, 0x45, 0xb9,
	0x31, 0x71, 0xe5, 0x58, 0x1a, 0x57, 0x8d, 0xe5, 0x11, 0xea, 0xd2, 0x8c, 0x8d, 0x58, 0x9c, 0xd1,
	0x28, 0x16, 0x3c, 0xa5, 0x69, 0x44, 0xb4, 0xc8, 0x59, 0xe2, 0xce, 0xc3, 0xe8, 0x3b, 0x35, 0x3a,
	0x00, 0x70, 0x17, 0x30, 0xfc, 0x14, 0x79, 0x89, 0xc8, 0x73, 0xa6, 0xf5, 0x84, 0x6f, 0x0a, 0xc7,
	0x65, 0x3a, 0xa2, 0xba, 0x56, 0x37, 0x41, 0xbd, 0xfc, 0x9b, 0xb5, 0x0b, 0xa4, 0x01, 0x70, 0x6c,
	0x92, 0x2d, 0x74, 0xcb, 0x8e, 0xb8, 0x90, 0xa2, 0x62, 0x8a, 0x09, 0x5e, 0xab, 0xff, 0x02, 0xf5,
	0xa2, 0x81, 0x87, 0x35, 0x6a, 0x75, 0x7d, 0x84, 0x53, 0xa6, 0xb4, 0x64, 0x71, 0xa9, 0x4f, 0xed,
	0xb6, 0x40, 0xf2, 0xdf, 0x19, 0xc4, 0xd2, 0x77, 0x90, 0xab, 0x85, 0x26, 0x59, 0x74, 0x89, 0xa8,
	0x0d, 0xa2, 0x2e, 0xe0, 0xcf, 0x2e, 0x2a, 0x7b, 0x5d, 0xd4, 0x81, 0x0d, 0xee, 0x49, 0x4a, 0x54,
	0x29, 0xc7, 0xf5, 0x6a, 0xf7, 0xd0, 0xe2, 0x85, 0xb8, 0xdd, 0x6d, 0x07, 0xcd, 0xa7, 0x94, 0x8b,
	0xdc, 0xfe, 0xb6, 0xe6, 0x03, 0xdf, 0x45, 0xff, 0xc4, 0x24, 0x23, 0x3c, 0xa1, 0x75, 0xd9, 0x59,
	0x80, 0x17, 0x6c, 0xd4, 0x54, 0x7b, 0xf8, 0xa1, 0x81, 0xe6, 0x21, 0x2d, 0xfe, 0xe8, 0xa0, 0xa6,
	0x39, 0x0a, 0xfc, 0xd8, 0xbf, 0xf6, 0xf8, 0xfc, 0x3f, 0x6f, 0x6b, 0x69, 0x6b, 0x5a, 0x99, 0x69,
	0xa0, 0xb7, 0xf1, 0xf6, 0xdb, 0xcf, 0xf7, 0xb3, 0xeb, 0xf8, 0x7e, 0x70, 0xfd, 0x13, 0x51, 0x18,
	0x87, 0x60, 0x16, 0xf6, 0x34, 0x85, 0xd9, 0xb3, 0x97, 0x32, 0x85, 0xd9, 0x73, 0x97, 0x34, 0x9d,
	0x59, 0xe3, 0xf0, 0x93, 0x83, 0x5a, 0xf5, 0xd6, 0xf0, 0xf6, 0x4d, 0xeb, 0x5e, 0xd8, 0xff, 0xd2,
	0xce, 0xf4, 0x42, 0x6b, 0x79, 0x13, 0x2c, 0xf7, 0xf1, 0xfa, 0x0d, 0x2c, 0x6b, 0x2b, 0x1e, 0xbc,
	0xf8, 0x7a, 0xec, 0x39, 0x47, 0xc7, 0x9e, 0xf3, 0xe3, 0xd8, 0x73, 0xde, 0x9d, 0x78, 0x33, 0x47,
	0x27, 0xde, 0xcc, 0xf7, 0x13, 0x6f, 0xe6, 0xd5, 0x93, 0x11, 0xd3, 0xfb, 0x65, 0xec, 0x27, 0x22,
	0x0f, 0x0e, 0x99, 0x4e, 0x04, 0xe3, 0x7d, 0x21, 0x47, 0x41, 0x21, 0x54, 0x3f, 0xd9, 0x27, 0x8c,
	0x07, 0x87, 0x97, 0x66, 0xd7, 0xe3, 0x82, 0xaa, 0xb8, 0x09, 0xaf, 0xf3, 0xe6, 0xaf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xe0, 0x00, 0x51, 0x1f, 0x0f, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the active policy and its on-chain authority.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Period returns the current funded reward period, when one exists.
	Period(ctx context.Context, in *QueryPeriodRequest, opts ...grpc.CallOption) (*QueryPeriodResponse, error)
	// Treasury returns the real balance of the non-minting module account.
	Treasury(ctx context.Context, in *QueryTreasuryRequest, opts ...grpc.CallOption) (*QueryTreasuryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.validatorincentives.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Period(ctx context.Context, in *QueryPeriodRequest, opts ...grpc.CallOption) (*QueryPeriodResponse, error) {
	out := new(QueryPeriodResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.validatorincentives.v1.Query/Period", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Treasury(ctx context.Context, in *QueryTreasuryRequest, opts ...grpc.CallOption) (*QueryTreasuryResponse, error) {
	out := new(QueryTreasuryResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.validatorincentives.v1.Query/Treasury", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the active policy and its on-chain authority.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Period returns the current funded reward period, when one exists.
	Period(context.Context, *QueryPeriodRequest) (*QueryPeriodResponse, error)
	// Treasury returns the real balance of the non-minting module account.
	Treasury(context.Context, *QueryTreasuryRequest) (*QueryTreasuryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Period(ctx context.Context, req *QueryPeriodRequest) (*QueryPeriodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Period not implemented")
}
func (*UnimplementedQueryServer) Treasury(ctx context.Context, req *QueryTreasuryRequest) (*QueryTreasuryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Treasury not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.validatorincentives.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Period_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Period(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.validatorincentives.v1.Query/Period",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Period(ctx, req.(*QueryPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Treasury_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTreasuryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Treasury(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.validatorincentives.v1.Query/Treasury",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Treasury(ctx, req.(*QueryTreasuryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.evm.validatorincentives.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Period",
			Handler:    _Query_Period_Handler,
		},
		{
			MethodName: "Treasury",
			Handler:    _Query_Treasury_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/evm/validatorincentives/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RewardPeriodBlocks != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RewardPeriodBlocks))
		i--
		dAtA[i] = 0x20
	}
	if m.BlocksPerYear != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BlocksPerYear))
		i--
		dAtA[i] = 0x18
	}
	if m.AnnualRateBasisPoints != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AnnualRateBasisPoints))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPeriodRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPeriodRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPeriodRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryPeriodResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPeriodResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPeriodResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TotalDistributedAtomic) > 0 {
		i -= len(m.TotalDistributedAtomic)
		copy(dAtA[i:], m.TotalDistributedAtomic)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TotalDistributedAtomic)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.DistributedAtomic) > 0 {
		i -= len(m.DistributedAtomic)
		copy(dAtA[i:], m.DistributedAtomic)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DistributedAtomic)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.PeriodProvisionAtomic) > 0 {
		i -= len(m.PeriodProvisionAtomic)
		copy(dAtA[i:], m.PeriodProvisionAtomic)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PeriodProvisionAtomic)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CommittedAnnualBudgetAtomic) > 0 {
		i -= len(m.CommittedAnnualBudgetAtomic)
		copy(dAtA[i:], m.CommittedAnnualBudgetAtomic)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CommittedAnnualBudgetAtomic)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.EligibleBondedAtomic) > 0 {
		i -= len(m.EligibleBondedAtomic)
		copy(dAtA[i:], m.EligibleBondedAtomic)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EligibleBondedAtomic)))
		i--
		dAtA[i] = 0x2a
	}
	if m.AnnualRateBasisPoints != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AnnualRateBasisPoints))
		i--
		dAtA[i] = 0x20
	}
	if m.EndBlock != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EndBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.StartBlock != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.StartBlock))
		i--
		dAtA[i] = 0x10
	}
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryTreasuryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTreasuryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTreasuryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTreasuryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTreasuryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTreasuryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BalanceAtomic) > 0 {
		i -= len(m.BalanceAtomic)
		copy(dAtA[i:], m.BalanceAtomic)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BalanceAtomic)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AnnualRateBasisPoints != 0 {
		n += 1 + sovQuery(uint64(m.AnnualRateBasisPoints))
	}
	if m.BlocksPerYear != 0 {
		n += 1 + sovQuery(uint64(m.BlocksPerYear))
	}
	if m.RewardPeriodBlocks != 0 {
		n += 1 + sovQuery(uint64(m.RewardPeriodBlocks))
	}
	return n
}

func (m *QueryPeriodRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryPeriodResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Active {
		n += 2
	}
	if m.StartBlock != 0 {
		n += 1 + sovQuery(uint64(m.StartBlock))
	}
	if m.EndBlock != 0 {
		n += 1 + sovQuery(uint64(m.EndBlock))
	}
	if m.AnnualRateBasisPoints != 0 {
		n += 1 + sovQuery(uint64(m.AnnualRateBasisPoints))
	}
	l = len(m.EligibleBondedAtomic)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.CommittedAnnualBudgetAtomic)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.PeriodProvisionAtomic)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.DistributedAtomic)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.TotalDistributedAtomic)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTreasuryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTreasuryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.BalanceAtomic)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnnualRateBasisPoints", wireType)
			}
			m.AnnualRateBasisPoints = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AnnualRateBasisPoints |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksPerYear", wireType)
			}
			m.BlocksPerYear = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksPerYear |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPeriodBlocks", wireType)
			}
			m.RewardPeriodBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RewardPeriodBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPeriodRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPeriodRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPeriodRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPeriodResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPeriodResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPeriodResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlock", wireType)
			}
			m.StartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndBlock", wireType)
			}
			m.EndBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnnualRateBasisPoints", wireType)
			}
			m.AnnualRateBasisPoints = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AnnualRateBasisPoints |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EligibleBondedAtomic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EligibleBondedAtomic = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommittedAnnualBudgetAtomic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommittedAnnualBudgetAtomic = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeriodProvisionAtomic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeriodProvisionAtomic = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributedAtomic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistributedAtomic = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDistributedAtomic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalDistributedAtomic = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTreasuryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTreasuryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTreasuryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTreasuryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTreasuryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTreasuryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BalanceAtomic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BalanceAtomic = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
