name: Solhint
# This workflow is only run when a .sol file has been changed
on:
  workflow_dispatch:

permissions: read-all

jobs:
  solhint:
    name: runner / solhint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af # v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/**.sol
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        if: env.GIT_DIFF
      - run: npm install -g solhint@v5.0.5
        if: env.GIT_DIFF
      - run: solhint --version
        if: env.GIT_DIFF
      - run: solhint '**/*.sol'
        if: env.GIT_DIFF
